### ISSUE TITLE
Cordova 编译不成功

### ISSUE THREAD

**Issue by junmin** [baomingba/cordova-plugin-qq#1]
你好~ 编译的时候出现下面的错误，请问会是什么原因呢？谢谢

$ cordova build android
Running command: /Users/junmin/Downloads/projects/sadecv/mht-app/hooks/after_prepare/010_add_platform_class.js /Users/junmin/Downloads/projects/sadecv/mht-app
add to body class: platform-android
Running command: /Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/cordova/build
ANDROID_HOME=/Users/junmin/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home
Running: /Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/gradlew cdvBuildDebug -b /Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava
/Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/src/com/qiudao/cordova/qq/QQ.java:65: error: cannot access Fragment
                tencent.login(activity, SCOPE, listener);
                       ^
  class file for android.support.v4.app.Fragment not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:compileDebugJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileDebugJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.554 secs

/Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /Users/junmin/Downloads/projects/sadecv/mht-app/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by junmin** [comment]
原来差了一个android-support-v4.jar 包，解决了。:D
